server:
  port: 8081
grpc:
  server:
    port: 9091

spring:
  application:
    name: auth-service

  autoconfigure:
    exclude: org.springframework.grpc.autoconfigure.server.GrpcServerFactoryAutoConfiguration
  
  datasource:
    url: jdbc:postgresql://localhost:5432/vinaacademy_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      grpc-port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    vn.vinaacademy.auth: DEBUG
    org.springframework.security: DEBUG